version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  test: # this can be any name you choose
    executor: python/default # use the default executor defined within the orb
    steps:
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: |
            pip install -r requirements.txt
            pycodestyle *.py
            coverage run --branch test_calculadora.py
            coverage report --fail-under=95
            python3 test_calculadora.py
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  

